In [10]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
# from .feature_utils import time_domain_features
# from .mahalanobis_distance import mahalanobis_distance

In [17]:
combined_data = pd.DataFrame(columns=["小時", "分", "秒", "毫秒", "垂直加速度", "水平加速度"])

data_list = []
folder_name = './viberation_dataset/Learning_set/Bearing1_1/'
files = [file for file in sorted(os.listdir(folder_name)) if 'acc' in file]
print(len(files))


2803


In [18]:
for file in files :
    df = pd.read_csv(f'{folder_name}/{file}', header=None)
    df = df.drop(5, axis=1)
    index = df.iloc[:, -1].argmax()
    df = df.iloc[index, :].to_frame().T

    data_list += df.values.tolist()
    
data = np.array(data_list)

In [28]:
print(type(data))
print(data.size)

<class 'numpy.ndarray'>
14015


In [31]:
print(data[:15])

[[9.0000e+00 3.9000e+01 3.9000e+01 1.5605e+05 2.0100e+00]
 [9.0000e+00 3.9000e+01 4.9000e+01 1.1316e+05 1.7250e+00]
 [9.0000e+00 3.9000e+01 5.9000e+01 8.1640e+04 1.7760e+00]
 [9.0000e+00 4.0000e+01 9.0000e+00 1.4172e+05 1.8780e+00]
 [9.0000e+00 4.0000e+01 1.9000e+01 1.3766e+05 1.7670e+00]
 [9.0000e+00 4.0000e+01 2.9000e+01 1.0590e+05 1.8520e+00]
 [9.0000e+00 4.0000e+01 3.9000e+01 1.3457e+05 1.8740e+00]
 [9.0000e+00 4.0000e+01 4.9000e+01 8.8554e+04 1.8890e+00]
 [9.0000e+00 4.0000e+01 5.9000e+01 1.5109e+05 2.1010e+00]
 [9.0000e+00 4.1000e+01 9.0000e+00 1.2047e+05 1.7380e+00]
 [9.0000e+00 4.1000e+01 1.9000e+01 1.1793e+05 2.5420e+00]
 [9.0000e+00 4.1000e+01 2.9000e+01 9.6093e+04 1.9160e+00]
 [9.0000e+00 4.1000e+01 3.9000e+01 1.3016e+05 1.7920e+00]
 [9.0000e+00 4.1000e+01 4.9000e+01 1.0152e+05 2.0090e+00]
 [9.0000e+00 4.1000e+01 5.9000e+01 8.8007e+04 1.6950e+00]]
