In [4]:
import random
import time
import numpy as np

In [2]:
def VAR_init(var, X): #_init
    
    if var in [0]: X[var] = random.randint(1, 512) # of hidden neurons
    elif var in [1]: X[var] = random.randint(1, 99) # dropout ratio
   
    elif var in [2]:  X[var] = random.randint(1, 512) # of hidden neurons
    elif var in [3]:  X[var] = random.randint(1, 99) # dropout ratio
          
    elif var in [4]:  X[var] = random.randint(1, 512) # of hidden neurons
    elif var in [5]:  X[var] = random.randint(1, 99) # dropout ratio 
        
    elif var in [6]:  X[var] = random.randint(1, 99)

In [6]:
Nrun, Ngen, Nsol, Nvar = 30, 10, 5, 7
pX = np.zeros([Nsol, Nvar], dtype = int)

for run in range(0, Nrun):
    X  = np.zeros([Nsol, Nvar], dtype = int)

for sol in range(0, Nsol):
    print("----- sol_{} -----".format(sol))
    for var in range(Nvar):
        VAR_init(var, X[sol]) #_init           
        pX[sol][var] = X[sol][var] # 每一個解的pbest
    
    print(X[sol])

----- sol_0 -----
[151  59 356  94 324  26  75]
----- sol_1 -----
[340  85 223  96 316  56  52]
----- sol_2 -----
[193  45 249  54 333  99  53]
----- sol_3 -----
[408  56 408  28 352  48  96]
----- sol_4 -----
[ 81  65 442  79 371   4  59]


In [ ]:
def ORIGIN(X): #_init
    global run, df
    
#     print("*****ORIGIN*****\n")
    print("=============== ORIGIN ===============")
    
    
    X[0], X[1] = 10, 20
    X[2], X[3] = 40, 20
    X[4], X[5] = 100, 20
    X[6] = 50        
    
    
    t0   = time.process_time()
    F[0] = Model(X)
    t1   = time.process_time()
    pT[0] = (t1 - t0)/60
        
    new_row = {'F': F[0], 'time': pT[0], 
               'pbest': F[0], 'pbest(var0)': X[0], 'pbest(var1)': X[1], 'pbest(var2)': X[2], 
               'pbest(var3)': X[3],'pbest(var4)': X[4], 'pbest(var5)': X[5], 'pbest(var6)': X[6],
                'gbest(var0)': X[0], 'gbest(var1)': X[1], 'gbest(var2)': X[2], 
                'gbest(var3)': X[3],'gbest(var4)': X[4], 'gbest(var5)': X[5]
                , 'gbest(var6)': X[6]}
    df = df.append(new_row, ignore_index=True)
    
    print("Origin_sol_set: ({}, {}, {}, {}, {}, {}, {})".format(X[0], X[1], X[2], X[3], X[4], X[5], X[6]))
    print("sol_fitness: {:^.4f}".format(F[0]))
    print("time: {:^.2f} mins\n".format(pT[0]))



In [ ]:


def SSO_init(X, F, pX, pF, Nsol, Nvar):
    
    global gBest, df
    print("*****SSO_INIT*****\n")
    print("=============== Generation_0 ===============")
    
    for sol in range(0, Nsol):
        print("----- sol_{} -----".format(sol))
        for var in range(Nvar):
            VAR_init(var, X[sol]) #_init           
            pX[sol][var] = X[sol][var] # 每一個解的pbest
        #print(X[sol])
        
        t0 = time.process_time()
        
        
        F[sol] = Model(X[sol])
        pF[sol] = F[sol]
                
        t1 = time.process_time()
        pT[sol] = (t1 - t0)/60
        
        print("Initialize sol_set_{}:({}, {}, {}, {}, {}, {}, {})".format(sol, X[sol][0], X[sol][1], X[sol][2], X[sol][3], X[sol][4], X[sol][5], X[sol][6]))
        print("Initialize pbest_fitness_{}: {:^.4f}".format(sol, pF[sol]))
        print("time: {:^.2f} mins\n".format(pT[sol]))
        
        if F[sol] > F[gBest]:
            gBest = sol   
        
        new_row = {'gen': gen, 'sol': sol, 'F': F[sol], 'time': pT[sol], 
                   'pbest': pF[sol], 'pbest(var0)': pX[sol][0], 'pbest(var1)': pX[sol][1], 'pbest(var2)': pX[sol][2], 
                   'pbest(var3)': pX[sol][3],'pbest(var4)': pX[sol][4], 'pbest(var5)': pX[sol][5], 'pbest(var6)': pX[sol][6],
                   'gbest(gen)': genBest, 'gbest(sol)': gBest, 'gbest(F)': pF[gBest], 
                    'gbest(var0)': pX[gBest][0], 'gbest(var1)': pX[gBest][1], 'gbest(var2)': pX[gBest][2], 
                   'gbest(var3)': pX[gBest][3],'gbest(var4)': pX[gBest][4], 'gbest(var5)': pX[gBest][5]
                      ,'gbest(var6)': pX[gBest][6]}
        df = df.append(new_row, ignore_index=True)
        
    print("Initialize gbest_fitness: {:^.4f}\n".format(F[gBest])) 